// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonavixxHub.Api.Infrastructure;

#nullable disable

namespace MonavixxHub.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324193950_FlashcardSet")]
    partial class FlashcardSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("MonavixxHub.Api.Common.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReferenceCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("MonavixxHub.Api.Features.Auth.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MonavixxHub.Api.Features.Flashcards.Models.Flashcard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Back")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Front")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Transcription")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("MonavixxHub.Api.Features.Flashcards.Models.FlashcardSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentSetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentSetId");

                    b.ToTable("FlashcardSets");
                });

            modelBuilder.Entity("MonavixxHub.Api.Features.Flashcards.Models.FlashcardSetEntry", b =>
                {
                    b.Property<Guid>("FlashcardId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlashcardSetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("FlashcardId", "FlashcardSetId");

                    b.HasIndex("FlashcardSetId");

                    b.ToTable("FlashcardSetEntries");
                });

            modelBuilder.Entity("MonavixxHub.Api.Features.Flashcards.Models.Flashcard", b =>
                {
                    b.HasOne("MonavixxHub.Api.Common.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MonavixxHub.Api.Features.Auth.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MonavixxHub.Api.Features.Flashcards.Models.FlashcardSet", b =>
                {
                    b.HasOne("MonavixxHub.Api.Features.Auth.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonavixxHub.Api.Features.Flashcards.Models.FlashcardSet", "ParentSet")
                        .WithMany("Subsets")
                        .HasForeignKey("ParentSetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");

                    b.Navigation("ParentSet");
                });

            modelBuilder.Entity("MonavixxHub.Api.Features.Flashcards.Models.FlashcardSetEntry", b =>
                {
                    b.HasOne("MonavixxHub.Api.Features.Flashcards.Models.Flashcard", "Flashcard")
                        .WithMany("Entries")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonavixxHub.Api.Features.Flashcards.Models.FlashcardSet", "FlashcardSet")
                        .WithMany("Entries")
                        .HasForeignKey("FlashcardSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flashcard");

                    b.Navigation("FlashcardSet");
                });

            modelBuilder.Entity("MonavixxHub.Api.Features.Flashcards.Models.Flashcard", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("MonavixxHub.Api.Features.Flashcards.Models.FlashcardSet", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Subsets");
                });
#pragma warning restore 612, 618
        }
    }
}
